# Generated by Django 5.0.12 on 2025-02-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('heading2', models.CharField(max_length=100)),
                ('imgSrc', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('students', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
