# Generated by Django 5.0.12 on 2025-02-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='clases',
            field=models.IntegerField(default=0),
        ),
    ]
