# Generated by Django 5.0.12 on 2025-02-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_clases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='clases',
            new_name='classes',
        ),
    ]
