# Generated by Django 5.0.12 on 2025-02-10 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_clases_courses_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='seller',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
