# Generated by Django 5.0.12 on 2025-02-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
    ]
