# Generated by Django 5.0.12 on 2025-02-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
